FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package*.json frontend/tsconfig.json frontend/vite.config.ts frontend/index.html ./frontend/
COPY frontend/.env ./frontend/
WORKDIR /app/frontend
RUN npm install
COPY frontend/src ./src
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/frontend/dist /usr/share/nginx/html/aq-monitor